name: Build OpenWrt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用 Ubuntu 22.04 环境

    steps:
    # 检出代码
    - name: Checkout
      uses: actions/checkout@v4

    # 安装依赖
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        python3-distutils python3-setuptools rsync swig unzip zlib1g-dev \
        file wget

    # 下载 OpenWrt 源码
    - name: Clone OpenWrt source
      run: |
        git clone https://github.com/openwrt/openwrt.git -b v24.10.0
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    # 配置 OpenWrt
    - name: Configure OpenWrt
      run: |
        cd openwrt
        # 创建 MiWiFi R4 的配置
        cat << EOF > .config
        CONFIG_TARGET_ramips=y
        CONFIG_TARGET_ramips_mt7621=y
        CONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_miwifi-r4=y
        CONFIG_PACKAGE_kmod-batman-adv=y
        CONFIG_PACKAGE_kmod-bonding=y
        CONFIG_PACKAGE_batctl=y
        CONFIG_PACKAGE_luci=y
        CONFIG_ALL_KMODS=y
        CONFIG_ALL_NONSHARED=y
        EOF
        make defconfig

    # 编译固件
    - name: Build OpenWrt
      run: |
        cd openwrt
        make -j$(nproc) V=s

    # 上传固件
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/ramips/mt7621/*.bin
